# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author: Carlos Schults
title:
  en: carlos schults / blog
  pt: carlos schults / blog
email: carlos.schults@gmail.com
description:
  en: Articles on software development, databases and several tech related subjects.
  pt: Artigos sobre desenvolvimento de software, banco de dados e vários assuntos ligados à tecnologia.
index:
  en:
  pt: pt.html
feed:
  en: /feed.xml
  pt: /rss.xml
baseurl: "" # the subpath of your site, e.g. /blog
homeurl:
    en: ""
    pt: "/pt"
url: "http://carlosschults.net" # the base hostname & protocol for your site
twitter_username: carlosschults
github_username:  carlosschults
excerpt_separator: <!--more-->  # you can specify your own separator, of course.


# Build settings
markdown: kramdown
